version: "3.7"

services:
    db:
        container_name: smh_page
        command: "--default-authentication-plugin=mysql_native_password"
        build:
            context: ./db
            dockerfile: local.Dockerfile
            args:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "${MYSQL_PORT}:3306"
        user: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ../../_data/db:/var/lib/mysql
