version: "3.7"

services:
    nginx:
        container_name: smh_nginx
        build:
          context: ..
          dockerfile: docker/nginx/local.Dockerfile
        restart: on-failure
        volumes:
          - ../:/var/www/html:rw
        ports:
          - "${NGINX_PORT}:80"
        depends_on:
          - php
        command: "nginx -c /etc/nginx/nginx.conf \"-g daemon off;\""
    php:
        container_name: smh_php
        build:
          context: ..
          dockerfile: docker/php/local.Dockerfile
          args:
            PUID: ${PUID}
            PGID: ${PGID}
        restart: on-failure

        volumes:
          - ../:/var/www/html:rw
        extra_hosts:
          - host.docker.internal:host-gateway
